custom_action_enabled: true
enabled: true
execution_interval: 30
integrations:
  api_enabled: false
  api_endpoint: https://api.example.com
  api_key: ${API_KEY}
max_executions: 100
name: testeragent
settings:
  debug_mode: false
  log_level: INFO
